project:
  type: website
  output-dir: docs

execute:
  freeze: auto

toc: false
# number-sections: true

website:
  title: "HomePage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/DJRamosA/HomePage
          - text: Report a Bug
            href:  https://github.com/DJRamosA/HomePage/issues/new

format:
  html:
    theme: Darkly
    css: styles.css
    smooth-scroll: true
    



